// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bvs
arma::mat bvs(arma::mat y, arma::mat Z, arma::mat a, arma::mat Gamma, arma::mat Sigma_i, arma::vec pos_res, arma::vec lpr_prior_0, arma::vec lpr_prior_1);
RcppExport SEXP _bvartools_bvs(SEXP ySEXP, SEXP ZSEXP, SEXP aSEXP, SEXP GammaSEXP, SEXP Sigma_iSEXP, SEXP pos_resSEXP, SEXP lpr_prior_0SEXP, SEXP lpr_prior_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_i(Sigma_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pos_res(pos_resSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lpr_prior_0(lpr_prior_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lpr_prior_1(lpr_prior_1SEXP);
    rcpp_result_gen = Rcpp::wrap(bvs(y, Z, a, Gamma, Sigma_i, pos_res, lpr_prior_0, lpr_prior_1));
    return rcpp_result_gen;
END_RCPP
}
// feir
arma::mat feir(arma::mat A, int h);
RcppExport SEXP _bvartools_feir(SEXP ASEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(feir(A, h));
    return rcpp_result_gen;
END_RCPP
}
// kalman_dk
arma::mat kalman_dk(arma::mat y, arma::mat Z, arma::mat Sigma_v, arma::mat Sigma_w, arma::mat B, arma::vec a_init, arma::mat Sigma_w_init);
RcppExport SEXP _bvartools_kalman_dk(SEXP ySEXP, SEXP ZSEXP, SEXP Sigma_vSEXP, SEXP Sigma_wSEXP, SEXP BSEXP, SEXP a_initSEXP, SEXP Sigma_w_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_v(Sigma_vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_w(Sigma_wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_init(a_initSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_w_init(Sigma_w_initSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_dk(y, Z, Sigma_v, Sigma_w, B, a_init, Sigma_w_init));
    return rcpp_result_gen;
END_RCPP
}
// loglik_gauss
arma::vec loglik_gauss(arma::mat y, arma::mat Sigma, arma::mat Sigma_i);
RcppExport SEXP _bvartools_loglik_gauss(SEXP ySEXP, SEXP SigmaSEXP, SEXP Sigma_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_i(Sigma_iSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_gauss(y, Sigma, Sigma_i));
    return rcpp_result_gen;
END_RCPP
}
// post_normal
arma::vec post_normal(arma::mat y, arma::mat x, arma::mat Sigma_i, arma::vec bprior, arma::mat Vprior_i);
RcppExport SEXP _bvartools_post_normal(SEXP ySEXP, SEXP xSEXP, SEXP Sigma_iSEXP, SEXP bpriorSEXP, SEXP Vprior_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_i(Sigma_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type bprior(bpriorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vprior_i(Vprior_iSEXP);
    rcpp_result_gen = Rcpp::wrap(post_normal(y, x, Sigma_i, bprior, Vprior_i));
    return rcpp_result_gen;
END_RCPP
}
// post_normal_sur
arma::vec post_normal_sur(arma::mat y, arma::mat Z, arma::mat Sigma_i, arma::vec bprior, arma::mat Vprior_i);
RcppExport SEXP _bvartools_post_normal_sur(SEXP ySEXP, SEXP ZSEXP, SEXP Sigma_iSEXP, SEXP bpriorSEXP, SEXP Vprior_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_i(Sigma_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type bprior(bpriorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vprior_i(Vprior_iSEXP);
    rcpp_result_gen = Rcpp::wrap(post_normal_sur(y, Z, Sigma_i, bprior, Vprior_i));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bvartools_bvs", (DL_FUNC) &_bvartools_bvs, 8},
    {"_bvartools_feir", (DL_FUNC) &_bvartools_feir, 2},
    {"_bvartools_kalman_dk", (DL_FUNC) &_bvartools_kalman_dk, 7},
    {"_bvartools_loglik_gauss", (DL_FUNC) &_bvartools_loglik_gauss, 3},
    {"_bvartools_post_normal", (DL_FUNC) &_bvartools_post_normal, 5},
    {"_bvartools_post_normal_sur", (DL_FUNC) &_bvartools_post_normal_sur, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_bvartools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
