# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.VarNormalGammaCoefficients <- function(object) {
    .Call(`_bvartools_VarNormalGammaCoefficients`, object)
}

.VarNormalGammaForecasts <- function(object) {
    .Call(`_bvartools_VarNormalGammaForecasts`, object)
}

.VarNormalGammaLogLik <- function(object) {
    .Call(`_bvartools_VarNormalGammaLogLik`, object)
}

.VarNormalStochvolCoefficients <- function(object) {
    .Call(`_bvartools_VarNormalStochvolCoefficients`, object)
}

.VarNormalStochvolForecasts <- function(object) {
    .Call(`_bvartools_VarNormalStochvolForecasts`, object)
}

.VarNormalStochvolLogLik <- function(object) {
    .Call(`_bvartools_VarNormalStochvolLogLik`, object)
}

.VarNormalWishartCoefficients <- function(object) {
    .Call(`_bvartools_VarNormalWishartCoefficients`, object)
}

.VarNormalWishartForecasts <- function(object) {
    .Call(`_bvartools_VarNormalWishartForecasts`, object)
}

.VarNormalWishartLogLik <- function(object) {
    .Call(`_bvartools_VarNormalWishartLogLik`, object)
}

.VarTvpGammaCoefficients <- function(object) {
    .Call(`_bvartools_VarTvpGammaCoefficients`, object)
}

.VarTvpGammaForecasts <- function(object) {
    .Call(`_bvartools_VarTvpGammaForecasts`, object)
}

.VarTvpGammaLogLik <- function(object) {
    .Call(`_bvartools_VarTvpGammaLogLik`, object)
}

.VarTvpStochvolCoefficients <- function(object) {
    .Call(`_bvartools_VarTvpStochvolCoefficients`, object)
}

.VarTvpStochvolForecasts <- function(object) {
    .Call(`_bvartools_VarTvpStochvolForecasts`, object)
}

.VarTvpStochvolLogLik <- function(object) {
    .Call(`_bvartools_VarTvpStochvolLogLik`, object)
}

.VarTvpWishartCoefficients <- function(object) {
    .Call(`_bvartools_VarTvpWishartCoefficients`, object)
}

.VarTvpWishartForecasts <- function(object) {
    .Call(`_bvartools_VarTvpWishartForecasts`, object)
}

.VarTvpWishartLogLik <- function(object) {
    .Call(`_bvartools_VarTvpWishartLogLik`, object)
}

.VecKlgs2010Coefficients <- function(object) {
    .Call(`_bvartools_VecKlgs2010Coefficients`, object)
}

.VecKlgs2010Forecasts <- function(object) {
    .Call(`_bvartools_VecKlgs2010Forecasts`, object)
}

.VecKlgs2010LogLik <- function(object) {
    .Call(`_bvartools_VecKlgs2010LogLik`, object)
}

.VecNormalGammaCoefficients <- function(object) {
    .Call(`_bvartools_VecNormalGammaCoefficients`, object)
}

.VecNormalGammaForecasts <- function(object) {
    .Call(`_bvartools_VecNormalGammaForecasts`, object)
}

.VecNormalGammaLogLik <- function(object) {
    .Call(`_bvartools_VecNormalGammaLogLik`, object)
}

.VecNormalStochvolCoefficients <- function(object) {
    .Call(`_bvartools_VecNormalStochvolCoefficients`, object)
}

.VecNormalStochvolForecasts <- function(object) {
    .Call(`_bvartools_VecNormalStochvolForecasts`, object)
}

.VecNormalStochvolLogLik <- function(object) {
    .Call(`_bvartools_VecNormalStochvolLogLik`, object)
}

.VecNormalWishartCoefficients <- function(object) {
    .Call(`_bvartools_VecNormalWishartCoefficients`, object)
}

.VecNormalWishartForecasts <- function(object) {
    .Call(`_bvartools_VecNormalWishartForecasts`, object)
}

.VecNormalWishartLogLik <- function(object) {
    .Call(`_bvartools_VecNormalWishartLogLik`, object)
}

.VecTvpGammaCoefficients <- function(object) {
    .Call(`_bvartools_VecTvpGammaCoefficients`, object)
}

.VecTvpGammaForecasts <- function(object) {
    .Call(`_bvartools_VecTvpGammaForecasts`, object)
}

.VecTvpGammaLogLik <- function(object) {
    .Call(`_bvartools_VecTvpGammaLogLik`, object)
}

.VecTvpStochvolCoefficients <- function(object) {
    .Call(`_bvartools_VecTvpStochvolCoefficients`, object)
}

.VecTvpStochvolForecasts <- function(object) {
    .Call(`_bvartools_VecTvpStochvolForecasts`, object)
}

.VecTvpStochvolLogLik <- function(object) {
    .Call(`_bvartools_VecTvpStochvolLogLik`, object)
}

.VecTvpWishartCoefficients <- function(object) {
    .Call(`_bvartools_VecTvpWishartCoefficients`, object)
}

.VecTvpWishartForecasts <- function(object) {
    .Call(`_bvartools_VecTvpWishartForecasts`, object)
}

.VecTvpWishartLogLik <- function(object) {
    .Call(`_bvartools_VecTvpWishartLogLik`, object)
}

#' Cointegration Reparameterisation
#' 
#' Performs the second transformation of the loading and
#' cointegration matrix as proposed in Koop et al. (2010).
#' 
#' @param alpha a \eqn{K \times r} matrix.
#' @param beta an \eqn{M \times r} matrix.
#' 
#' @details The function performs two transformations:
#' \itemize{
#'   \item \eqn{A = \alpha (\beta^{\prime} \beta)^{1/2}}
#'   \item \eqn{B = \beta (\beta^{\prime} \beta)^{-1/2}}
#' }
#' 
#' @references
#' Koop, G., León-González, R., & Strachan R. W. (2010). Efficient posterior
#' simulation for cointegrated models with priors on the cointegration space.
#' \emph{Econometric Reviews, 29}(2), 224-242. \doi{10.1080/07474930903382208}
#' 
#' @return A list of two matrices:
#' \item{alpha}{Loading matrix \eqn{A}.}
#' \item{beta}{Cointegration matrix \eqn{B} (semiorthogonal).}
#' 
#' @examples
#' 
#' # Generate input data
#' alpha <- matrix(c(-0.07, 0.17), 2)
#' beta <- matrix(c(1, -4), 2)
#' 
#' # Reparameterise
#' coint_kls2010_reparameterise_two(alpha, beta)
#' 
coint_kls2010_reparameterise_two <- function(alpha, beta) {
    .Call(`_bvartools_coint_kls2010_reparameterise_two`, alpha, beta)
}

#' Posterior Data Preparation
#' 
#' Generates the input matrix for the simulation of the cointegration matrix \eqn{\beta}.
#' 
#' @param w a \eqn{T \times M} matrix.
#' @param alpha a \eqn{K \times r} matrix of the loading matrix \eqn{\alpha}.
#' @param k integer of the number of endogenous variables in the model.
#' @param r integer with the rank of the cointegration matrix \eqn{\Pi}.
#' @param reparameterise logical indicating if the reparameterisation described
#' in Koop et al. (2010) should be performed.
#' @param tvp logical indicating if the SUR matrix with the values of regressors
#' should be prepared for the estimation of constant or time varying parameters.
#' 
#' @return A sparse block matrix.
#' 
#' @examples
#' 
#' data("e6") # Load data
#' 
#' # Generate model input
#' mod <- create_bvecmodel(e6, p = 4, r = 1,
#'                         const = "unrestricted", seasonal = "unrestricted")
#' 
#' # Obtain input data
#' alpha <- matrix(c(-0.1, 0.16, -0.04, -0.02), 2)
#' w <- mod$data$train$w
#' 
#' # Constant coefficients
#' coint_prepare_sur_data(w, alpha, 2, 1, TRUE, FALSE)
#' 
#' # Time varying coefficients
#' coint_prepare_sur_data(w, alpha, 2, 1, FALSE, TRUE)
#' 
#' 
coint_prepare_sur_data <- function(w, alpha, k, r, reparameterise, tvp) {
    .Call(`_bvartools_coint_prepare_sur_data`, w, alpha, k, r, reparameterise, tvp)
}

#' Covariance: Data Preparation
#'
#' Convenience function, which generates the input data for posterior
#' simulation of covariance parameters.
#'
#' @param y a \eqn{KT \times 1} vector of input data.
#' @param omega_i a \eqn{K \times K} or \eqn{KT \times KT} matrix of error variances.
#' The matrix must be sparse.
#' @param k an integer of the number of endogenous variables.
#' @param tt an integer of the number of observations.
#' @param tvp logical indicating if the SUR matrix with the values of regressors
#' should be prepared for the estimation of constant or time varying parameters.
#' 
#' @details For the model
#' \deqn{y_t = Z_{t} a_t + u_t}
#' with \eqn{u_t \sim N(0, \Psi \Omega_{t} \Psi^{\prime})} and \eqn{\Omega_{t}}
#' as a diagonal matrix of error variances, the function produces
#' the input data for the posterior simulation of the lower triangular covariance coefficients
#' of \eqn{\Psi} as presented in Primiceri (2005).
#' 
#' @return A list with three elements:
#' \item{y}{The prepared vector of endogenous variables.}
#' \item{z}{The prepared matrix of regressors.}
#' \item{omega_i}{The prepared diagonal matrix of measurement error variances.}
#' All matrices are returned as sparse matrices.
#' 
#' @references
#' 
#' Chan, J., Koop, G., Poirier, D. J., & Tobias J. L. (2019). \emph{Bayesian econometric methods} (2nd ed.). Cambridge: Cambridge University Press.
#' 
#' Primiceri, G. E. (2005). Time varying structural vector autoregressions and monetary policy. \emph{The Review of Economic Studies 72}(3), 821--852. \doi{10.1111/j.1467-937X.2005.00353.x}
#' 
#' @examples
#' 
#' k <- 3
#' tt <- 4
#' u <- matrix(1:(k * tt))
#'   
#' # Generate simple variance matrix
#' omega_i <- Matrix::Matrix(diag(1:k, k))
#' # Generate block diagonal variance matrix
#' tv_omega_i <- Matrix::Matrix(0, k * tt, k * tt)
#' for (i in 1:tt) {
#'   tv_omega_i[(i - 1) * k + 1:k, (i - 1) * k + 1:k] <- omega_i
#' }
#' 
#' # Constant error variances
#' 
#' # Constant coefficients
#' covar_prepare_data(u, omega_i, k, tt, FALSE)
#' # Time varying coefficients
#' covar_prepare_data(u, omega_i, k, tt, TRUE)
#' 
#' 
#' # Time varying error variances
#' 
#' # Constant coefficients
#' covar_prepare_data(u, tv_omega_i, k, tt, FALSE)
#' # Time varying coefficients
#' covar_prepare_data(u, tv_omega_i, k, tt, TRUE)
#' 
covar_prepare_data <- function(y, omega_i, k, tt, tvp) {
    .Call(`_bvartools_covar_prepare_data`, y, omega_i, k, tt, tvp)
}

#' Covariance: Vector to Matrix
#'
#' Convenience function, which takes the vector of draws of lower triangular
#' covariance coefficients and transforms it into a matrix with ones on the main
#' diagonal. In case of time varying parameters the resulting matrix will be
#' block diagonal.
#'
#' @param psi a \eqn{K (K - 1) / 2 \times 1} or \eqn{T K (K - 1) / 2 \times 1} vector of input data.
#' @param k the number \eqn{K} of endogenous variables.
#' @param tt the number \eqn{T} of observations.
#' 
#' @return A sparse, block diagonal matrix.
#' 
#' @references
#' 
#' Chan, J., Koop, G., Poirier, D. J., & Tobias J. L. (2019). \emph{Bayesian econometric methods} (2nd ed.). Cambridge: Cambridge University Press.
#' 
#' Primiceri, G. E. (2005). Time varying structural vector autoregressions and monetary policy. \emph{The Review of Economic Studies 72}(3), 821--852. \doi{10.1111/j.1467-937X.2005.00353.x}
#' 
#' @examples
#' 
#' # Create artificial data
#' k <- 5
#' tt <- 4
#' n_covar <- (k - 1) * k / 2
#' 
#' # Constant parameters
#' psi <- matrix(1:(n_covar))
#' covar_vector_to_matrix(psi, k, tt)
#' 
#' # Time varying parameters
#' psi <- matrix(1:(n_covar * tt))
#' covar_vector_to_matrix(psi, k, tt)
#' 
covar_vector_to_matrix <- function(psi, k, tt) {
    .Call(`_bvartools_covar_vector_to_matrix`, psi, k, tt)
}

.draw_forecast <- function(k, p, a0_i, use_a, a, sigma, pred) {
    .Call(`_bvartools_draw_forecast`, k, p, a0_i, use_a, a, sigma, pred)
}

.generate_forecasts <- function(k, p, h, use_a, z, draws_a, draws_u_sigma_inv) {
    .Call(`_bvartools_generate_forecasts`, k, p, h, use_a, z, draws_a, draws_u_sigma_inv)
}

#' Posterior Data Preparation
#' 
#' Generates a lower triangular block matrix with ones on the main diagonal,
#' where the off-diagonal elements are blocks.
#' 
#' @param a \eqn{K^2p}-dimensional vector of coefficients. See 'Details'.
#' @param k integer of the number of columns per block.
#' @param tt integer specifying 
#' 
#' @return A sparse matrix.
#' 
#' @details For the \eqn{K \times Kp} matrix A, where \eqn{a = vec(A)}, with
#' \eqn{A = \left[A_1, A_2, ..., A_p\right]} the function constructs the
#' following sparse \eqn{KT \times KT} diagonal block matrix:
#' \deqn{\begin{bmatrix} I_{K}  & 0 & 0 & 0 & \dots & 0 \\-A_{1} & I_{K} & 0 & 0 & \dots & 0 \\-A_{2} & -A_{1}& I_{K} & 0 & \dots & 0 \\ 0 & -A_{2}& -A_{1}& I_{K} & \dots & 0 \\ \vdots & \ddots& \ddots& \ddots& \ddots& 0 \\  0 & \dots & 0 & -A_{2}& -A_{1}& I_{K} \end{bmatrix}.}
#' 
#' @examples
#' a <- matrix(1:8)
#' generate_lower_block_diagonal(a, 2, 5)
#' 
generate_lower_block_diagonal <- function(a, k, tt) {
    .Call(`_bvartools_generate_lower_block_diagonal`, a, k, tt)
}

.ir <- function(A, h, type, impulse, response) {
    .Call(`_bvartools_ir`, A, h, type, impulse, response)
}

#' Durbin and Koopman Simulation Smoother
#'
#' An implementation of the Kalman filter and backward smoothing
#' algorithm proposed by Durbin and Koopman (2002).
#'
#' @param y a \eqn{K \times T} matrix of endogenous variables.
#' @param z a \eqn{KT \times M} matrix of explanatory variables.
#' @param sigma_u the constant \eqn{K \times K} error variance-covariance matrix.
#' For time varying variance-covariance matrices a \eqn{KT \times K} can be specified.
#' @param sigma_v the constant \eqn{M \times M} coefficient variance-covariance matrix.
#' For time varying variance-covariance matrices a \eqn{MT \times M} can be specified.
#' @param B the constant \eqn{M \times M} autocorrelation matrix of the transition
#' equation. For a time varying transition an \eqn{MT \times M} matrix can be specified.
#' @param a_init an M-dimensional vector of initial states.
#' @param P_init an \eqn{M \times M} variance-covariance matrix of the initial states.
#'
#' @details The function uses algorithm 2 from Durbin and Koopman (2002) to produce
#' a draw of the state vector \eqn{a_t} for \eqn{t = 1,...,T} for a state space model
#' with measurement equation
#' \deqn{y_t = Z_t a_t + u_t}
#' and transition equation
#' \deqn{a_{t + 1} = B_t a_{t} + v_t,}
#' where \eqn{u_t \sim N(0, \Sigma_{u,t})} and \eqn{v_t \sim N(0, \Sigma_{v,t})}.
#' \eqn{y_t} is a K-dimensional vector of endogenous variables and
#' \eqn{Z_t = z_t^{\prime} \otimes I_K} is a \eqn{K \times M} matrix of regressors with
#' \eqn{z_t} as a vector of regressors.
#'
#' The algorithm takes into account Jarociński (2015), where a possible missunderstanding
#' in the implementation of the algorithm of Durbin and Koopman (2002) is pointed out. Following
#' that note the function sets the mean of the initial state to zero in the first step of the algorithm.
#'
#' This is the routine the time varying parameter samplers of the package use. It
#' comes from the vendored BayesTS core, so there is one implementation of the
#' smoother rather than one for R and one for the samplers.
#'
#' The draw uses R's random number generator, so \code{\link{set.seed}} makes it
#' reproducible.
#'
#' @return A \eqn{M \times T+1} matrix of state vector draws. Column \eqn{i} is
#' the state the observation in column \eqn{i} of \code{y} loads on, for
#' \eqn{i = 1,...,T}, so a caller wanting one state per observation takes the
#' first \eqn{T} columns. The first column is not a state preceding the sample:
#' it is \eqn{a_1}, already conditioned on every observation. The last column is
#' the transition applied once past the end of the sample and is informed by no
#' observation; it is returned because the recursions build it on the way.
#'
#' @examples
#'
#' # Load data
#' data("e1")
#' data <- diff(log(e1))
#'
#' # Generate model data
#' temp <- create_bvarmodel(data = data, p = 2, deterministic = "const",
#'                          iterations = 1, burnin = 0)
#' y <- t(temp$data$train$y)
#' z <- temp$data$train$z
#' k <- nrow(y)
#' tt <- ncol(y)
#' m <- ncol(z)
#'
#' # Priors
#' a_mu_prior <- matrix(0, m)
#' a_v_i_prior <- diag(0.1, m)
#'
#' a_Q <- diag(.0001, m)
#'
#' # Initial value of Sigma
#' sigma <- tcrossprod(y) / tt
#' sigma_i <- solve(sigma)
#'
#' # Initial values for Kalman filter
#' y_init <- y * 0
#' a_filter <- matrix(0, m, tt + 1)
#'
#' # Initialise the Kalman filter
#' for (i in 1:tt) {
#'   y_init[, i] <- y[, i] - z[(i - 1) * k + 1:k,] %*% a_filter[, i]
#' }
#' a_init <- post_normal_sur(y = y_init, z = z, sigma_i = sigma_i,
#'                           a_prior = a_mu_prior, v_i_prior = a_v_i_prior)
#' y_filter <- matrix(y) - z %*% a_init
#' y_filter <- matrix(y_filter, k) # Reshape
#'
#' # Kalman filter and backward smoother
#' a_filter <- kalman_durbin_koopman_2002(y = y_filter, z = z, sigma_u = sigma,
#'                                        sigma_v = a_Q, B = diag(1, m),
#'                                        a_init = matrix(0, m), P_init = a_Q)
#'
#' a <- a_filter + matrix(a_init, m, tt + 1)
#'
#' @references
#'
#' Durbin, J., & Koopman, S. J. (2002). A simple and efficient simulation smoother for
#' state space time series analysis. \emph{Biometrika, 89}(3), 603--615.
#'
#' Jarociński, M. (2015). A note on implementing the Durbin and Koopman simulation
#' smoother. \emph{Computational Statistics and Data Analysis, 91}, 1--3.
#' \doi{10.1016/j.csda.2015.05.001}
#'
#' @export
kalman_durbin_koopman_2002 <- function(y, z, sigma_u, sigma_v, B, a_init, P_init) {
    .Call(`_bvartools_kalman_durbin_koopman_2002_export`, y, z, sigma_u, sigma_v, B, a_init, P_init)
}

.log_likelihood_normal <- function(k, u, sigma_inv) {
    .Call(`_bvartools_log_likelihood_normal`, k, u, sigma_inv)
}

#' Calculates the log-likelihood of a multivariate normal distribution.
#' 
#' @param u a \eqn{K \times T} matrix of residuals.
#' @param sigma a \eqn{K \times K} or \eqn{KT \times K} variance-covariance matrix.
#' 
#' @details The log-likelihood is calculated for each vector in period \eqn{t} as
#' \deqn{-\frac{K}{2} \ln 2\pi - \frac{1}{2} \ln |\Sigma_t| -\frac{1}{2} u_t^\prime \Sigma_t^{-1} u_t},
#' where \eqn{u_t = y_t - \mu_t}.
#' 
#' @examples
#' 
#' # Load data
#' data("e1")
#' e1 <- diff(log(e1))
#' 
#' # Generate VAR model
#' data <- create_bvarmodel(e1, p = 2, deterministic = "const")
#' y <- t(data$data$train$y)
#' x <- t(data$data$train$x)
#'
#' # LS estimate
#' ols <- tcrossprod(y, x) %*% solve(tcrossprod(x))
#' 
#' # Residuals
#' u <- y - ols %*% x # Residuals
#'
#' # Covariance matrix
#' sigma <- tcrossprod(u) / ncol(u)
#' 
#' # Log-likelihood
#' loglik_normal(u = u, sigma = sigma)
#' 
loglik_normal <- function(u, sigma) {
    .Call(`_bvartools_loglik_normal`, u, sigma)
}

#' Bayesian Variable Selection
#' 
#' \code{post_bvs} employs Bayesian variable selection as proposed by Korobilis (2013)
#' to produce a vector of inclusion parameters for the coefficient matrix
#' of a VAR model.
#' 
#' @param y a \eqn{KT \times 1} vector of the endogenous variables.
#' @param z a \eqn{KT \times M} matrix of explanatory variables.
#' @param a an M-dimensional vector of parameter draws. If time varying parameters are used,
#' an \eqn{M \times T} coefficient matrix can be provided.
#' @param k integer of the number of endogenous variables.
#' @param m integer of the number of M 
#' @param lambda an \eqn{M \times M} inclusion matrix that should be updated.
#' @param sigma_i a sparse \eqn{KT \times KT} block diagonal matrix containing
#' the inverse variance-covariance matrix.
#' @param prob_prior an M-dimensional vector of prior inclusion probabilities.
#' @param include an integer vector specifying the positions of variables, which should be
#' included in the BVS algorithm. If \code{NULL} (default), BVS will be applied to all variables.
#' 
#' @details The function employs Bayesian variable selection as proposed
#' by Korobilis (2013) to produce a vector of inclusion parameters, which are
#' the diagonal elements of the inclusion matrix \eqn{\Lambda} for the VAR model
#' \deqn{y_t = Z_t \Lambda a_t + u_t,}
#' where \eqn{u_t \sim N(0, \Sigma_{t})}.
#' \eqn{y_t} is a K-dimensional vector of endogenous variables and
#' \eqn{Z_t = x_t^{\prime} \otimes I_K} is a \eqn{K \times M} matrix of regressors with
#' \eqn{x_t} as a vector of regressors.
#' 
#' @return A matrix of inclusion parameters on its diagonal.
#' 
#' @examples
#' 
#' # Load data
#' data("e1")
#' e1 <- diff(log(e1)) * 100
#' 
#' # Generate model input, which uses BVS as variable selection algorithm
#' object <- create_bvarmodel(data = e1, p = 2, deterministic = "const",
#'                            varsel = "bvs")
#' 
#' # Add prior specifications, including the prior inclusion probabilities
#' object <- add_priors(object,
#'                      coef = list(v_i = 1, v_i_det = 1 / 10),
#'                      sigma = list(df = "k", scale = 1),
#'                      varsel = list(inprior = .1))
#' 
#' # Add initial values
#' object <- add_initial_values(object)
#' 
#' # Obtain data, initial values and priors
#' y <- matrix(t(object[["data"]][["train"]][["y"]]))
#' z <- object[["data"]][["train"]][["z"]] # Argument 'z' is taken dense
#' k <- object[["model"]][["k"]]
#' tt <- nrow(object[["data"]][["train"]][["y"]])
#' m <- ncol(z)
#' a <- object[["initial"]][["a"]]
#' prob_prior <- object[["priors"]][["a"]][["inprior"]]
#' 
#' # Arguments 'lambda' and 'sigma_i' have to be sparse
#' lambda <- Matrix::Matrix(diag(1, m), sparse = TRUE)
#' 
#' # Initial value of the inverse error covariance matrix
#' u <- matrix(y - z %*% a, k)
#' sigma_i <- Matrix::Matrix(kronecker(diag(1, tt), solve(tcrossprod(u) / tt)),
#'                           sparse = TRUE)
#' 
#' # Draw inclusion parameters
#' post_bvs(y, z, a, k, m, lambda, sigma_i, prob_prior)
#' 
#' @references
#' 
#' Korobilis, D. (2013). VAR forecasting using Bayesian variable selection.
#' \emph{Journal of Applied Econometrics, 28}(2), 204--230. \doi{10.1002/jae.1271}
#' 
post_bvs <- function(y, z, a, k, m, lambda, sigma_i, prob_prior, include = NULL) {
    .Call(`_bvartools_post_bvs`, y, z, a, k, m, lambda, sigma_i, prob_prior, include)
}

#' Posterior Draw for Cointegration Models
#' 
#' Produces a draw of coefficients for cointegration models with a prior on
#' the cointegration space as proposed in Koop et al. (2010) and a draw of
#' non-cointegration coefficients from a normal density.
#' 
#' @param y a \eqn{K \times T} matrix of differenced endogenous variables.
#' @param beta a \eqn{M \times r} cointegration matrix \eqn{\beta}.
#' @param w a \eqn{M \times T} matrix of variables in the cointegration term.
#' @param x a \eqn{N \times T} matrix of differenced regressors and unrestricted deterministic terms.
#' @param sigma_i an inverse of the \eqn{K \times K} variance-covariance matrix.
#' @param v_i a numeric between 0 and 1 specifying the shrinkage of the cointegration space prior.
#' @param p_tau_i an inverted \eqn{M \times M} matrix specifying the central location
#' of the cointegration space prior of \eqn{sp(\beta)}.
#' @param g_i a \eqn{K \times K} matrix.
#' @param gamma_mu_prior a \eqn{KN \times 1} prior mean vector of non-cointegration coefficients.
#' @param gamma_v_i_prior an inverted \eqn{KN \times KN} prior covariance matrix of non-cointegration coefficients.
#' 
#' @details The function produces posterior draws of the coefficient
#' matrices \eqn{\alpha}, \eqn{\beta} and \eqn{\Gamma} for the model
#' \deqn{y_{t} = \alpha \beta^{\prime} w_{t-1} + \Gamma z_{t} + u_{t},}
#' where \eqn{y_{t}} is a K-dimensional vector of differenced endogenous variables.
#' \eqn{w_{t}} is an \eqn{M \times 1} vector of variables in the cointegration term,
#' which include lagged values of endogenous and exogenous variables in levels and
#' restricted deterministic terms. \eqn{z_{t}} is an N-dimensional vector of
#' differenced endogenous and exogenous explanatory variabes as well as unrestricted
#' deterministic terms. The error term is \eqn{u_t \sim \Sigma}.
#' 
#' Draws of the loading matrix \eqn{\alpha} are obtained using the prior on the cointegration space
#' as proposed in Koop et al. (2010). The posterior covariance matrix is
#' \deqn{\overline{V}_{\alpha} = \left[\left(v^{-1} (\beta^{\prime} P_{\tau}^{-1} \beta) \otimes G_{-1}\right) + \left(ZZ^{\prime} \otimes \Sigma^{-1} \right) \right]^{-1}}
#' and the posterior mean by
#' \deqn{\overline{\alpha} = \overline{V}_{\alpha} + vec(\Sigma^{-1} Y Z^{\prime}),}
#' where \eqn{Y} is a \eqn{K \times T} matrix of differenced endogenous variables and
#' \eqn{Z = \beta^{\prime} W} with \eqn{W} as an \eqn{M \times T} matrix of
#' variables in the cointegration term.
#' 
#' For a given prior mean vector \eqn{\underline{\Gamma}} and prior covariance matrix \eqn{\underline{V_{\Gamma}}}
#' the posterior covariance matrix of non-cointegration coefficients in \eqn{\Gamma} is obtained by
#' \deqn{\overline{V}_{\Gamma} = \left[ \underline{V}_{\Gamma}^{-1} + \left(X X^{\prime} \otimes \Sigma^{-1} \right) \right]^{-1}}
#' and the posterior mean by
#' \deqn{\overline{\Gamma} = \overline{V}_{\Gamma} \left[ \underline{V}_{\Gamma}^{-1} \underline{\Gamma} + vec(\Sigma^{-1} Y X^{\prime}) \right],}
#' where \eqn{X} is an \eqn{M \times T} matrix of
#' explanatory variables, which do not enter the cointegration term.
#' 
#' Draws of the cointegration matrix \eqn{\beta} are obtained using the prior on the cointegration space
#' as proposed in Koop et al. (2010). The posterior covariance matrix of the unrestricted cointegration
#' matrix \eqn{B} is
#' \deqn{\overline{V}_{B} = \left[\left(A^{\prime} G^{-1} A \otimes v^{-1} P_{\tau}^{-1} \right) + \left(A^{\prime} \Sigma^{-1} A \otimes WW^{\prime} \right) \right]^{-1}}
#' and the posterior mean by
#' \deqn{\overline{B} = \overline{V}_{B} + vec(W Y_{B}^{-1} \Sigma^{-1} A),}
#' where \eqn{Y_{B} = Y - \Gamma X} and \eqn{A = \alpha (\alpha^{\prime} \alpha)^{-\frac{1}{2}}}.
#' 
#' The final draws of \eqn{\alpha} and \eqn{\beta} are calculated using
#' \eqn{\beta = B (B^{\prime} B)^{-\frac{1}{2}}} and
#' \eqn{\alpha = A (B^{\prime} B)^{\frac{1}{2}}}.
#' 
#' @return A named list containing the following elements:
#' \item{alpha}{a draw of the \eqn{K \times r} loading matrix.}
#' \item{beta}{a draw of the \eqn{M \times r} cointegration matrix.}
#' \item{Pi}{a draw of the \eqn{K \times M} cointegration matrix \eqn{\Pi = \alpha \beta^{\prime}}.}
#' \item{Gamma}{a draw of the \eqn{K \times N} coefficient matrix for non-cointegration parameters.}
#' 
#' @examples
#'  
#' # Load data
#' data("e6")
#' 
#' # Generate model data
#' temp <- create_bvecmodel(e6, p = 2, r = 1)
#' y <- t(temp$data$y)
#' w <- t(temp$data$w)
#' x <- t(temp$data$x)
#' 
#' k <- nrow(y) # Endogenous variables
#' tt <- ncol(y) # Number of observations
#' 
#' # Priors
#' gamma_mu_prior <- matrix(0, 6)
#' gamma_v_i_prior <- diag(0, 6)
#' 
#' # Initial value of Sigma
#' sigma <- tcrossprod(y) / tt
#' sigma_i <- solve(sigma)
#' 
#' # Initial values of beta
#' beta <- matrix(c(1, -4), k)
#' 
#' # Draw parameters
#' coint <- post_coint_kls(y = y, beta = beta, w = ect, x = x, sigma_i = sigma_i,
#'                         v_i = 0, p_tau_i = diag(1, k), g_i = sigma_i,
#'                         gamma_mu_prior = gamma_mu_prior, gamma_v_i_prior = gamma_v_i_prior)
#' 
#' @references
#' 
#' Koop, G., León-González, R., & Strachan R. W. (2010). Efficient posterior
#' simulation for cointegrated models with priors on the cointegration space.
#' \emph{Econometric Reviews, 29}(2), 224-242. \doi{10.1080/07474930903382208}
#' 
post_coint_kls <- function(y, beta, w, sigma_i, v_i, p_tau_i, g_i, x = NULL, gamma_mu_prior = NULL, gamma_v_i_prior = NULL) {
    .Call(`_bvartools_post_coint_kls`, y, beta, w, sigma_i, v_i, p_tau_i, g_i, x, gamma_mu_prior, gamma_v_i_prior)
}

#' Posterior Draw for Cointegration Models
#' 
#' Produces a draw of coefficients for cointegration models in SUR form with a prior on
#' the cointegration space as proposed in Koop et al. (2010) and a draw of
#' non-cointegration coefficients from a normal density.
#' 
#' @param y a \eqn{K \times T} matrix of differenced endogenous variables.
#' @param beta a \eqn{M \times r} cointegration matrix \eqn{\beta}, where \eqn{\beta^{\prime} \beta = I}.
#' @param w a \eqn{M \times T} matrix of variables in the cointegration term.
#' @param x  a \eqn{KT \times NK} matrix of differenced regressors and unrestricted deterministic terms.
#' @param sigma_i the inverse of the constant \eqn{K \times K} error variance-covariance matrix.
#' For time varying variance-covariance matrics a \eqn{KT \times K} can be provided.
#' @param v_i a numeric between 0 and 1 specifying the shrinkage of the cointegration space prior.
#' @param p_tau_i an inverted \eqn{M \times M} matrix specifying the central location
#' of the cointegration space prior of \eqn{sp(\beta)}.
#' @param g_i a \eqn{K \times K} or \eqn{KT \times K} matrix. If the matrix is \eqn{KT \times K},
#' the function will automatically produce a \eqn{K \times K} matrix containing the means of the
#' time varying \eqn{K \times K} covariance matrix.
#' @param gamma_mu_prior a \eqn{KN \times 1} prior mean vector of non-cointegration coefficients.
#' @param gamma_v_i_prior an inverted \eqn{KN \times KN} prior covariance matrix of
#' non-cointegration coefficients.
#' @param svd logical. If \code{TRUE} the singular value decomposition is used to determine
#' the root of the posterior covariance matrix. Default is \code{FALSE} which means
#' that the eigenvalue decomposition is used.
#' 
#' @details The function produces posterior draws of the coefficient
#' matrices \eqn{\alpha}, \eqn{\beta} and \eqn{\Gamma} for the model
#' \deqn{y_{t} = \alpha \beta^{\prime} w_{t-1} + \Gamma z_{t} + u_{t},}
#' where \eqn{y_{t}} is a K-dimensional vector of differenced endogenous variables.
#' \eqn{w_{t}} is an \eqn{M \times 1} vector of variables in the cointegration term,
#' which include lagged values of endogenous and exogenous variables in levels and
#' restricted deterministic terms. \eqn{z_{t}} is an N-dimensional vector of
#' differenced endogenous and exogenous explanatory variabes as well as unrestricted
#' deterministic terms. The error term is \eqn{u_t \sim \Sigma}.
#' 
#' Draws of the loading matrix \eqn{\alpha} are obtained using the prior on the cointegration space
#' as proposed in Koop et al. (2010). The posterior covariance matrix is
#' \deqn{\overline{V}_{\alpha} = \left[\left(v^{-1} (\beta^{\prime} P_{\tau}^{-1} \beta) \otimes G_{-1}\right) + \left(ZZ^{\prime} \otimes \Sigma^{-1} \right) \right]^{-1}}
#' and the posterior mean by
#' \deqn{\overline{\alpha} = \overline{V}_{\alpha} + vec(\Sigma^{-1} Y Z^{\prime}),}
#' where \eqn{Y} is a \eqn{K \times T} matrix of differenced endogenous variables and
#' \eqn{Z = \beta^{\prime} W} with \eqn{W} as an \eqn{M \times T} matrix of
#' variables in the cointegration term.
#' 
#' For a given prior mean vector \eqn{\underline{\Gamma}} and prior covariance matrix \eqn{\underline{V_{\Gamma}}}
#' the posterior covariance matrix of non-cointegration coefficients in \eqn{\Gamma} is obtained by
#' \deqn{\overline{V}_{\Gamma} = \left[ \underline{V}_{\Gamma}^{-1} + \left(X X^{\prime} \otimes \Sigma^{-1} \right) \right]^{-1}}
#' and the posterior mean by
#' \deqn{\overline{\Gamma} = \overline{V}_{\Gamma} \left[ \underline{V}_{\Gamma}^{-1} \underline{\Gamma} + vec(\Sigma^{-1} Y X^{\prime}) \right],}
#' where \eqn{X} is an \eqn{M \times T} matrix of
#' explanatory variables, which do not enter the cointegration term.
#' 
#' Draws of the cointegration matrix \eqn{\beta} are obtained using the prior on the cointegration space
#' as proposed in Koop et al. (2010). The posterior covariance matrix of the unrestricted cointegration
#' matrix \eqn{B} is
#' \deqn{\overline{V}_{B} = \left[\left(A^{\prime} G^{-1} A \otimes v^{-1} P_{\tau}^{-1} \right) + \left(A^{\prime} \Sigma^{-1} A \otimes WW^{\prime} \right) \right]^{-1}}
#' and the posterior mean by
#' \deqn{\overline{B} = \overline{V}_{B} + vec(W Y_{B}^{-1} \Sigma^{-1} A),}
#' where \eqn{Y_{B} = Y - \Gamma X} and \eqn{A = \alpha (\alpha^{\prime} \alpha)^{-\frac{1}{2}}}.
#' 
#' The final draws of \eqn{\alpha} and \eqn{\beta} are calculated using
#' \eqn{\beta = B (B^{\prime} B)^{-\frac{1}{2}}} and
#' \eqn{\alpha = A (B^{\prime} B)^{\frac{1}{2}}}.
#' 
#' @return A named list containing the following elements:
#' \item{alpha}{a draw of the \eqn{K \times r} loading matrix.}
#' \item{beta}{a draw of the \eqn{M \times r} cointegration matrix.}
#' \item{Pi}{a draw of the \eqn{K \times M} cointegration matrix \eqn{\Pi = \alpha \beta^{\prime}}.}
#' \item{Gamma}{a draw of the \eqn{K \times N} coefficient matrix for non-cointegration parameters.}
#' 
#' @examples
#' 
#' # Load data
#' data("e6")
#' 
#' # Generate model data
#' temp <- create_bvecmodel(e6, p = 1, r = 1)
#' y <- t(temp$data$train$y)
#' ect <- t(temp$data$train$w)
#' 
#' k <- nrow(y) # Endogenous variables
#' tt <- ncol(y) # Number of observations
#' 
#' # Initial value of Sigma
#' sigma <- tcrossprod(y) / tt
#' sigma_i <- solve(sigma)
#' 
#' # Initial values of beta
#' beta <- matrix(c(1, -4), k)
#' 
#' # Draw parameters
#' coint <- post_coint_kls_sur(y = y, beta = beta, w = ect,
#'                             sigma_i = sigma_i, v_i = 0, p_tau_i = diag(1, nrow(ect)),
#'                             g_i = sigma_i)
#' 
#' @references
#' 
#' Koop, G., León-González, R., & Strachan R. W. (2010). Efficient posterior
#' simulation for cointegrated models with priors on the cointegration space.
#' \emph{Econometric Reviews, 29}(2), 224-242. \doi{10.1080/07474930903382208}
#' 
post_coint_kls_sur <- function(y, beta, w, sigma_i, v_i, p_tau_i, g_i, x = NULL, gamma_mu_prior = NULL, gamma_v_i_prior = NULL, svd = FALSE) {
    .Call(`_bvartools_post_coint_kls_sur`, y, beta, w, sigma_i, v_i, p_tau_i, g_i, x, gamma_mu_prior, gamma_v_i_prior, svd)
}

#' Posterior Draws of Error Variances
#' 
#' Produces a draw of the constant diagonal error variance matrix of the
#' measurement equation of a state space model using an inverse gamma posterior density.
#' 
#' @param u a \eqn{KT \times 1} vector of errors.
#' @param shape_prior a \eqn{K \times 1} vector of prior shape parameters.
#' @param rate_prior a \eqn{K \times 1} vector of prior rate parameters.
#' @param inverse logical. If \code{TRUE}, the function returns the precision matrix,
#' i.e. the inverse of the variance matrix. Defaults to \code{FALSE}.
#' 
#' @details For a model with measurement equation
#' \deqn{y_t = Z_{t} a_t + u_t}
#' with \eqn{u_t \sim N(0, \Sigma_{u})}
#' the function produces a draw of the constant diagonal error variance matrix
#' \eqn{\Sigma_u}.
#' 
#' @references
#' Chan, J., Koop, G., Poirier, D. J., & Tobias J. L. (2019). \emph{Bayesian econometric methods}
#' (2nd ed.). Cambridge: Cambridge University Press.
#' 
#' @examples
#' 
#' k <- 10 # Number of endogenous variables
#' tt <- 1000 # Number of observations
#' 
#' set.seed(1234) # Set RNG seed
#' 
#' # Generate artificial error series with N(0, 1)
#' u <- matrix(rnorm(k * tt))
#' 
#' # Define priors
#' shape_prior <- matrix(1, k)
#' rate_prior <- matrix(.0001, k)
#' 
#' # Obtain posterior draw
#' post_gamma_measurement_variance(u, shape_prior, rate_prior, inverse = FALSE)
#' 
#' @return A matrix.
#' 
post_gamma_measurement_variance <- function(u, shape_prior, rate_prior, inverse) {
    .Call(`_bvartools_post_gamma_measurement_variance`, u, shape_prior, rate_prior, inverse)
}

#' Posterior Draws of Error Variances
#' 
#' Produces a draw of the constant diagonal error variance matrix of the
#' state equation of a state space model using an inverse gamma posterior density.
#' 
#' @param a a \eqn{KT \times 1} vector of time varying parameter draws.
#' @param a_init a \eqn{K \times 1} vector of initial states.
#' @param shape_prior a \eqn{K \times 1} vector of prior shape parameters.
#' @param rate_prior a \eqn{K \times 1} vector of prior rate parameters.
#' @param inverse logical. If \code{TRUE}, the function returns the precision matrix,
#' i.e. the inverse of the variance matrix. Defaults to \code{FALSE}.
#' 
#' @details For the state space model with state equation
#' \deqn{a_t = a_{t-1} + v_t}
#' and measurement equation
#' \deqn{y_t = Z_{t} a_{t} + u_{t}}
#' with \eqn{v_t \sim N(0, \Sigma^{v})} and \eqn{u_t \sim N(0, \Sigma^{u})}
#' the function produces a draw of the constant diagonal error variances matrix of the
#' state equation \eqn{\Sigma^{v}}.
#' 
#' @references
#' Chan, J., Koop, G., Poirier, D. J., & Tobias J. L. (2019). \emph{Bayesian econometric methods}
#' (2nd ed.). Cambridge: Cambridge University Press.
#' 
#' @examples
#' k <- 10 # Number of artificial coefficients
#' tt <- 1000 # Number of observations
#' 
#' set.seed(1234) # Set RNG seed
#' 
#' # Generate artificial data according to a random walk
#' a <- matrix(rnorm(k), k, tt + 1)
#' for (i in 2:(tt + 1)) {
#'   a[, i] <- a[, i - 1] + rnorm(k, 0, sqrt(1 / 100))
#' }
#' 
#' a_init <- matrix(a[, 1]) # Define initial state
#' a <- matrix(a[, -1]) # Drop initial state from main sample and make vector
#' 
#' # Define priors
#' shape_prior <- matrix(1, k)
#' rate_prior <- matrix(.0001, k)
#' 
#' # Obtain posterior draw
#' post_gamma_state_variance(a, a_init, shape_prior, rate_prior, inverse = FALSE)
#' 
#' @return A matrix.
#' 
post_gamma_state_variance <- function(a, a_init, shape_prior, rate_prior, inverse) {
    .Call(`_bvartools_post_gamma_state_variance`, a, a_init, shape_prior, rate_prior, inverse)
}

#' Posterior Draw from a Normal Distribution
#' 
#' Produces a draw of coefficients from a normal posterior density.
#' 
#' @param y a \eqn{K \times T} matrix of endogenous variables.
#' @param x an \eqn{M \times T} matrix of explanatory variables.
#' @param sigma_i the inverse of the \eqn{K \times K} variance-covariance matrix.
#' @param a_prior a \eqn{KM \times 1} numeric vector of prior means.
#' @param v_i_prior the inverse of the \eqn{KM \times KM} prior covariance matrix.
#' 
#' @details The function produces a vectorised posterior draw \eqn{a} of the
#' \eqn{K \times M} coefficient matrix \eqn{A} for the model
#' \deqn{y_{t} = A x_{t} + u_{t},}
#' where \eqn{y_{t}} is a K-dimensional vector of endogenous variables,
#' \eqn{x_{t}} is an M-dimensional vector of explanatory variabes
#' and the error term is \eqn{u_t \sim \Sigma}.
#' 
#' For a given prior mean vector \eqn{\underline{a}} and prior covariance matrix \eqn{\underline{V}}
#' the posterior covariance matrix is obtained by
#' \deqn{\overline{V} = \left[ \underline{V}^{-1} + \left(X X^{\prime} \otimes \Sigma^{-1} \right) \right]^{-1}}
#' and the posterior mean by
#' \deqn{\overline{a} = \overline{V} \left[ \underline{V}^{-1} \underline{a} + vec(\Sigma^{-1} Y X^{\prime}) \right],}
#' where \eqn{Y} is a \eqn{K \times T} matrix of the endogenous variables and \eqn{X} is an \eqn{M \times T} matrix of
#' the explanatory variables.
#' 
#' @examples
#' 
#' # Load data
#' data("e1")
#' data <- diff(log(e1))
#' 
#' # Generate model data
#' temp <- create_bvarmodel(data, p = 2, deterministic = "const")
#' y <- t(temp$data$train$y)
#' x <- t(temp$data$train$x)
#' k <- nrow(y)
#' tt <- ncol(y)
#' m <- k * nrow(x)
#' 
#' # Priors
#' a_mu_prior <- matrix(0, m)
#' a_v_i_prior <- diag(0.1, m)
#' 
#' # Initial value of inverse Sigma
#' sigma_i <- solve(tcrossprod(y) / tt)
#' 
#' # Draw parameters
#' a <- post_normal(y = y, x = x, sigma_i = sigma_i,
#'                  a_prior = a_mu_prior, v_i_prior = a_v_i_prior)
#' 
#' @return A vector.
#' 
#' @references
#' 
#' Lütkepohl, H. (2006). \emph{New introduction to multiple time series analysis} (2nd ed.). Berlin: Springer.
#' 
post_normal <- function(y, x, sigma_i, a_prior, v_i_prior) {
    .Call(`_bvartools_post_normal`, y, x, sigma_i, a_prior, v_i_prior)
}

#' Posterior Draw from a Normal Distribution
#' 
#' Produces a draw of coefficients from a normal posterior density for
#' a model with seemingly unrelated regresssions (SUR).
#' 
#' @param y a \eqn{K \times T} matrix of endogenous variables.
#' @param z a \eqn{KT \times M} matrix of explanatory variables.
#' @param sigma_i the inverse of the constant \eqn{K \times K} error variance-covariance matrix.
#' For time varying variance-covariance matrics a \eqn{KT \times K} can be provided.
#' @param a_prior a \eqn{M x 1} numeric vector of prior means.
#' @param v_i_prior the inverse of the \eqn{M x M} prior covariance matrix.
#' @param svd logical. If \code{TRUE} the singular value decomposition is used to determine
#' the root of the posterior covariance matrix. Default is \code{FALSE} which means
#' that the eigenvalue decomposition is used.
#' 
#' @details The function produces a posterior draw of the coefficient vector \eqn{a} for the model
#' \deqn{y_{t} = Z_{t} a + u_{t},}
#' where \eqn{u_t \sim N(0, \Sigma_{t})}.
#' \eqn{y_t} is a K-dimensional vector of endogenous variables and
#' \eqn{Z_t = z_t^{\prime} \otimes I_K} is a \eqn{K \times KM} matrix of regressors with
#' \eqn{z_t} as a vector of regressors.
#' 
#' For a given prior mean vector \eqn{\underline{a}} and prior covariance matrix \eqn{\underline{V}}
#' the posterior covariance matrix is obtained by
#' \deqn{\overline{V} = \left[ \underline{V}^{-1} + \sum_{t=1}^{T} Z_{t}^{\prime} \Sigma_{t}^{-1} Z_{t} \right]^{-1}}
#' and the posterior mean by
#' \deqn{\overline{a} = \overline{V} \left[ \underline{V}^{-1} \underline{a} + \sum_{t=1}^{T} Z_{t}^{\prime} \Sigma_{t}^{-1} y_{t}  \right].}
#' 
#' @examples
#' 
#' # Load data
#' data("e1")
#' data <- diff(log(e1))
#' 
#' # Generate model data
#' temp <- create_bvarmodel(data, p = 2, deterministic = "const")
#' y <- t(temp$data$train$y)
#' z <- temp$data$train$z
#' k <- nrow(y)
#' tt <- ncol(y)
#' m <- ncol(z)
#' 
#' # Priors
#' a_mu_prior <- matrix(0, m)
#' a_v_i_prior <- diag(0.1, m)
#' 
#' # Initial value of inverse Sigma
#' sigma_i <- solve(tcrossprod(y) / tt)
#'
#' # Draw parameters
#' a <- post_normal_sur(y = y, z = z, sigma_i = sigma_i,
#'                      a_prior = a_mu_prior, v_i_prior = a_v_i_prior)
#' 
#' @return A vector.
#' 
post_normal_sur <- function(y, z, sigma_i, a_prior, v_i_prior, svd = FALSE) {
    .Call(`_bvartools_post_normal_sur`, y, z, sigma_i, a_prior, v_i_prior, svd)
}

#' Connectedness table of one posterior draw
#'
#' The normalised forecast error variance decomposition table behind the
#' spillover index of Diebold and Yilmaz (2012): row \eqn{j} column \eqn{k} is
#' the share of the \eqn{h} step forecast error variance of variable \eqn{j}
#' that is attributed to a shock to variable \eqn{k}, and every row sums to one.
#'
#' Separate from \code{.vardecomp} rather than a loop over it, for two reasons.
#' The forecast error impulse responses do not depend on the response variable,
#' so filling the whole table in one pass costs what \code{.vardecomp} costs for
#' a single row of it. And the generalised decomposition here divides by the
#' variance of the \emph{impulse} variable, as in Pesaran and Shin (1998), which
#' is the quantity the spillover index is defined on; \code{.vardecomp} divides
#' by the standard deviation of the response instead, a factor that cancels
#' when a row is normalised and so cannot serve here.
#'
#' @param A a list with elements \code{A}, the k x kp coefficients of one draw,
#'   and \code{Sigma}, its k x k error covariance.
#' @param h an integer of the forecast horizon, at least one.
#' @param type either \code{"gir"} or \code{"oir"}.
#'
#' @noRd
.spillover_table <- function(A, h, type) {
    .Call(`_bvartools_spillover_table`, A, h, type)
}

#' Stochastic Volatility
#'
#' Produces a draw of log-volatilities based on Kim, Shephard and Chib (1998).
#'
#' @param y a \eqn{T \times K} matrix containing the time series.
#' @param h a \eqn{T \times K} matrix of the current draw of log-volatilities.
#' @param sigma a \eqn{K \times 1} vector of variances of log-volatilities,
#' where the \eqn{i}th element corresponds to the \eqn{i}th column in \code{y}.
#' Must be finite and positive.
#' @param h_init a \eqn{K \times 1} vector of the initial states of log-volatilities,
#' where the \eqn{i}th element corresponds to the \eqn{i}th column in \code{y}.
#' @param constant a \eqn{K \times 1} vector of constants that should be added to \eqn{y^2}
#' before taking the natural logarithm. The \eqn{i}th element corresponds to
#' the \eqn{i}th column in \code{y}. Must be finite and positive. See 'Details'.
#'
#' @details For each column in \code{y} the function produces a posterior
#' draw of the log-volatility \eqn{h} for the model
#' \deqn{y_{t} = e^{\frac{1}{2}h_t} \epsilon_{t},}
#' where \eqn{\epsilon_t \sim N(0, 1)} and \eqn{h_t} is assumed to evolve according to a random walk
#' \deqn{h_t = h_{t - 1} + u_t,}
#' with \eqn{u_t \sim N(0, \sigma^2)}.
#'
#' The implementation follows the algorithm of Kim, Shephard and Chib (1998)
#' and performs the following steps:
#' \enumerate{
#'   \item Perform the transformation \eqn{y_t^* = ln(y_t^2 + constant)}.
#'   \item Obtain a sample from the seven-component normal mixture for
#'   approximating the log-\eqn{\chi_1^2} distribution.
#'   \item Obtain a draw of log-volatilities.
#' }
#'
#' The posterior precision of the log-volatility is tridiagonal -- the random
#' walk contributes the two bands of \eqn{D^\prime D} and the mixture only a
#' diagonal -- so the draw is obtained from a banded Cholesky factorisation,
#' which costs \eqn{O(T)} rather than the \eqn{O(T^3)} of a dense one.
#'
#' The probabilities of the mixture components in step 2 are obtained in logs and
#' shifted by their period-wise maximum before they are exponentiated. Weighting
#' the component densities directly underflows to zero for all seven components
#' once an observation lies far enough out in their tails, which leaves the
#' probabilities of that period undefined and selects a component that does not
#' exist.
#'
#' The arguments are checked before the first draw and a violation raises an
#' error. \code{sigma} and \code{constant} have to be finite and positive, since
#' the algorithm divides by the former and takes the logarithm of a sum
#' containing the latter, and all three of \code{sigma}, \code{h_init} and
#' \code{constant} have to have one element per column of \code{y}.
#'
#' The draw uses R's random number generator, so \code{\link{set.seed}} makes it
#' reproducible.
#'
#' @return A \eqn{T \times K} matrix of log-volatility draws.
#'
#' @references
#'
#' Chan, J., Koop, G., Poirier, D. J., & Tobias J. L. (2019). \emph{Bayesian econometric methods}
#' (2nd ed.). Cambridge: Cambridge University Press.
#'
#' Kim, S., Shephard, N., & Chib, S. (1998). Stochastic volatility. Likelihood inference and comparison
#' with ARCH models. \emph{Review of Economic Studies 65}(3), 361--393. \doi{10.1111/1467-937X.00050}
#'
#' @examples
#' data("us_macrodata")
#' y <- diff(us_macrodata)
#' h_init <- log(diag(var(y)))
#' h <- t(matrix(h_init, 3, nrow(y)))
#' sigma_h <- rep(.05, 3)
#' const <- rep(.0001, 3)
#' stochvol_ksc_1998(y, h, sigma_h, h_init, const)
#'
#' @export
stochvol_ksc_1998 <- function(y, h, sigma, h_init, constant) {
    .Call(`_bvartools_stochvol_ksc_1998_export`, y, h, sigma, h_init, constant)
}

#' Stochastic Volatility
#'
#' Produces a draw of log-volatilities based on Omori, Chib, Shephard and Nakajima (2007).
#'
#' @param y a \eqn{T \times K} matrix containing the time series.
#' @param h a \eqn{T \times K} matrix of the current draw of log-volatilities.
#' @param sigma a \eqn{K \times 1} vector of variances of log-volatilities,
#' where the \eqn{i}th element corresponds to the \eqn{i}th column in \code{y}.
#' Must be finite and positive.
#' @param h_init a \eqn{K \times 1} vector of the initial states of log-volatilities,
#' where the \eqn{i}th element corresponds to the \eqn{i}th column in \code{y}.
#' @param constant a \eqn{K \times 1} vector of constants that should be added to \eqn{y^2}
#' before taking the natural logarithm. The \eqn{i}th element corresponds to
#' the \eqn{i}th column in \code{y}. Must be finite and positive. See 'Details'.
#'
#' @details For each column in \code{y} the function produces a posterior
#' draw of the log-volatility \eqn{h} for the model
#' \deqn{y_{t} = e^{\frac{1}{2}h_t} \epsilon_{t},}
#' where \eqn{\epsilon_t \sim N(0, 1)} and \eqn{h_t} is assumed to evolve according to a random walk
#' \deqn{h_t = h_{t - 1} + u_t,}
#' with \eqn{u_t \sim N(0, \sigma^2)}.
#'
#' The implementation follows the algorithm of Omori, Chib, Shephard and Nakajima (2007)
#' and performs the following steps:
#' \enumerate{
#'   \item Perform the transformation \eqn{y_t^* = ln(y_t^2 + constant)}.
#'   \item Obtain a sample from the ten-component normal mixture for
#'   approximating the log-\eqn{\chi_1^2} distribution.
#'   \item Obtain a draw of log-volatilities.
#' }
#'
#' The ten components approximate the log-\eqn{\chi_1^2} distribution more
#' closely than the seven of \code{\link{stochvol_ksc_1998}}, at a proportional
#' cost in the first step.
#'
#' The posterior precision of the log-volatility is tridiagonal -- the random
#' walk contributes the two bands of \eqn{D^\prime D} and the mixture only a
#' diagonal -- so the draw is obtained from a banded Cholesky factorisation,
#' which costs \eqn{O(T)} rather than the \eqn{O(T^3)} of a dense one.
#'
#' The probabilities of the mixture components in step 2 are obtained in logs and
#' shifted by their period-wise maximum before they are exponentiated. Weighting
#' the component densities directly underflows to zero for all ten components
#' once an observation lies far enough out in their tails, which leaves the
#' probabilities of that period undefined and selects a component that does not
#' exist.
#'
#' The arguments are checked before the first draw and a violation raises an
#' error. \code{sigma} and \code{constant} have to be finite and positive, since
#' the algorithm divides by the former and takes the logarithm of a sum
#' containing the latter, and all three of \code{sigma}, \code{h_init} and
#' \code{constant} have to have one element per column of \code{y}.
#'
#' The draw uses R's random number generator, so \code{\link{set.seed}} makes it
#' reproducible.
#'
#' @return A \eqn{T \times K} matrix of log-volatility draws.
#'
#' @references
#'
#' Chan, J., Koop, G., Poirier, D. J., & Tobias J. L. (2019). \emph{Bayesian econometric methods}
#' (2nd ed.). Cambridge: Cambridge University Press.
#'
#' Kim, S., Shephard, N., & Chib, S. (1998). Stochastic volatility. Likelihood inference and comparison
#' with ARCH models. \emph{Review of Economic Studies 65}(3), 361--393. \doi{10.1111/1467-937X.00050}
#'
#' Omori, Y., Chib, S., Shephard, N., & Nakajima, J. (2007). Stochastic volatiltiy with leverage. Fast and efficient likelihood inference.
#' \emph{Journal of Econometrics 140}(2), 425--449. \doi{10.1016/j.jeconom.2006.07.008}
#'
#' @examples
#' data("us_macrodata")
#' y <- diff(us_macrodata)
#' h_init <- log(diag(var(y)))
#' h <- t(matrix(h_init, 3, nrow(y)))
#' sigma_h <- rep(.05, 3)
#' const <- rep(.0001, 3)
#' stochvol_ocsn_2007(y, h, sigma_h, h_init, const)
#'
#' @export
stochvol_ocsn_2007 <- function(y, h, sigma, h_init, constant) {
    .Call(`_bvartools_stochvol_ocsn_2007_export`, y, h, sigma, h_init, constant)
}

#' SUR Matrix Transformation
#' 
#' Transforms a dense matrix of dimensions \eqn{KT \times M} into a sparse block
#' diagonal matrix of dimensions \eqn{KT \times MT}.
#' 
#' @param z a \eqn{KT \times M} matrix.
#' @param k integer of the number of endogenous variables.
#' @param tt integer of the number of observations.
#' 
#' @return A sparse block diagonal matrix of dimensions \eqn{KT \times MT}.
#' 
#' @examples
#' 
#' # Specify the dimensions of the dense matrix
#' k <- 2
#' tt <- 5
#' m <- 3
#' 
#' # Generate artificial data
#' z <- matrix(NA, k * tt, m)
#' for (i in 1:tt) {
#'   z[(i - 1) * k + 1:k, ] <- i
#' }
#' 
#' # Perform transformation
#' sur_const_to_tvp(z, k, tt)
#' 
#' 
sur_const_to_tvp <- function(z, k, tt) {
    .Call(`_bvartools_sur_const_to_tvp`, z, k, tt)
}

#' Stochastic Search Variable Selection
#' 
#' \code{ssvs} employs stochastic search variable selection as proposed by George et al. (2008)
#' to produce a draw of the precision matrix of the coefficients in a VAR model.
#' 
#' @param a an M-dimensional vector of coefficient draws.
#' @param tau0 an M-dimensional vector of prior standard deviations for restricted
#' coefficients in vector \code{a}.
#' @param tau1 an M-dimensional vector of prior standard deviations for unrestricted
#' coefficients in vector \code{a}.
#' @param prob_prior an M-dimensional vector of prior inclusion probabilites for the coefficients
#' in vector \code{a}.
#' @param include an integer vector specifying the positions of coefficients in vector \code{a}, which should be
#' included in the SSVS algorithm. If \code{NULL} (default), SSVS will be applied to all coefficients.
#' 
#' @details The function employs stochastic search variable selection (SSVS) as proposed
#' by George et al. (2008) to produce a draw of the diagonal inverse prior covariance matrix
#' \eqn{\underline{V}^{-1}} and the corresponding vector of inclusion parameters \eqn{\lambda}
#' of the vectorised coefficient matrix \eqn{a = vec(A)} for the VAR model
#' \deqn{y_t = A x_t + u_t,}
#' where \eqn{y_{t}} is a K-dimensional vector of endogenous variables,
#' \eqn{x_{t}} is a vector of explanatory variabes
#' and the error term is \eqn{u_t \sim \Sigma}.
#' 
#' @return A named list containing two components:
#' \item{v_i}{an \eqn{M \times M} inverse prior covariance matrix.}
#' \item{lambda}{an M-dimensional vector of inclusion parameters.}
#' 
#' @examples
#' 
#' # Load data
#' data("e1")
#' data <- diff(log(e1))
#' 
#' # Generate model data
#' temp <- create_bvarmodel(data, p = 2, deterministic = "const")
#' y <- t(temp$data$train$y)
#' x <- t(temp$data$train$x)
#' k <- nrow(y)
#' tt <- ncol(y)
#' m <- k * nrow(x)
#' 
#' # Obtain SSVS priors using the semiautomatic approach
#' priors <- ssvs_prior(temp, semiautomatic = c(0.1, 10))
#' tau0 <- priors$tau0
#' tau1 <- priors$tau1
#' 
#' # Prior for inclusion parameter
#' prob_prior <- matrix(0.5, m)
#' 
#' # Priors
#' a_mu_prior <- matrix(0, m)
#' a_v_i_prior <- diag(c(tau1^2), m)
#' 
#' # Initial value of Sigma
#' sigma_i <- solve(tcrossprod(y) / tt)
#' 
#' # Draw parameters
#' a <- post_normal(y = y, x = x, sigma_i = sigma_i,
#'                  a_prior = a_mu_prior, v_i_prior = a_v_i_prior)
#' 
#' # Run SSVS
#' lambda <- ssvs(a = a, tau0 = tau0, tau1 = tau1,
#'                prob_prior = prob_prior)
#' 
#' @references
#' 
#' George, E. I., Sun, D., & Ni, S. (2008). Bayesian stochastic search for VAR model
#' restrictions. \emph{Journal of Econometrics, 142}(1), 553--580.
#' \doi{10.1016/j.jeconom.2007.08.017}
#' 
ssvs <- function(a, tau0, tau1, prob_prior, include = NULL) {
    .Call(`_bvartools_ssvs`, a, tau0, tau1, prob_prior, include)
}

.vardecomp <- function(A, h, type, response) {
    .Call(`_bvartools_vardecomp`, A, h, type, response)
}

.VecToVarSpecification <- function(model) {
    .Call(`_bvartools_VecToVarSpecification`, model)
}

.VecToVarCoefficients <- function(object) {
    .Call(`_bvartools_VecToVarCoefficients`, object)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_bvartools_RcppExport_registerCCallable`)
})
