# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bayesian Variable Selection
#' 
#' Produces a draw of coefficients with a Minnesota Prior.
#' 
#' @param y a \eqn{n x T} matrix containing the time series of the dependent variable.
#' @param Z a \eqn{nT x m} matrix containing the time series of the explanatory variables.
#' @param a a \eqn{m x 1} or \eqn{m x T} matrix of parameter values for a model with
#' constant or time-varying coefficients, respectively.
#' @param Gamma a \eqn{m x 1} vector of inclusion parameters.
#' @param Sigma_i The inverse of the \eqn{n x n} variance-covariance matrix.
#' @param pos_res an integer vector specifying the paramters for which BVS should be applied.
#' @param lpr_prior_0 a \eqn{m x 1} vector of log inclusion probabilities, i.e. \eqn{ln(\pi)}.
#' @param lpr_prior_1 a \eqn{m x 1} vector of log inclusion probabilities, i.e. \eqn{ln(1 - \pi)}.
#' 
#' @details For the model
#' \deqn{y_t = Z_t \Gamma a_t + v_t,}
#' where \eqn{v_t \sim N(0, \Sigma)} the function produces of a draw of the inclusion
#' parameters \eqn{\gamma_i}.
#' 
#' @return A \eqn{m x 1} vector of inclusion parameters.
#' 
#' @references
#' 
#' Korobilis, D. (2013). VAR forecasting using Bayesian variable selection. \emph{Journal of Applied Econometrics}, 28(2), 204--230.
#' 
bvs <- function(y, Z, a, Gamma, Sigma_i, pos_res, lpr_prior_0, lpr_prior_1) {
    .Call(`_bvartools_bvs`, y, Z, a, Gamma, Sigma_i, pos_res, lpr_prior_0, lpr_prior_1)
}

#' Forecast Error Impulse Response
#' 
#' Produces a forecast error impulse response matrix of a vector autoregressive model.
#' 
#' @param A \eqn{n x np} matrix of coefficients, where \eqn{n} is the number of endogenous
#' variables and \eqn{p} is the number of lags.
#' @param h integer specifying the steps.
#' 
#' @details The function produces the moving average representation \eqn{\Phi_i} for the model
#' \deqn{y_t = \sum_{i}^{p} A_i y_{t - i} + \epsilon_{t}}
#' by recursions
#' \deqn{\Phi_i = \sum_{j = 1}^{i} \Phi_{i - j} A_j}
#' for \eqn{i = 1, 2, ...} and starting with \eqn{\Phi_0 = I_K}.
#' 
#' @return a \eqn{nh x n} matrix.
#' 
feir <- function(A, h = 5L) {
    .Call(`_bvartools_feir`, A, h)
}

#' Durbin and Koopman Simulation Smoother
#' 
#' The function is an implementation of the Kalman filter and backward smoothing
#' algorithm proposed by Durbin and Koopman (2002).
#' 
#' @param y a \eqn{n x T} matrix containing the time series of the dependent variable.
#' @param Z a \eqn{nT x m} matrix containing the time series of the explanatory variables.
#' @param Sigma_v a \eqn{n x n} or \eqn{nT x n} variance-covariance matrix.
#' @param Sigma_w a \eqn{m x m} variance-covariance matrix of the transition equation.
#' @param B a \eqn{m x m} autocorrelation function of the transition equation.
#' @param a_init a \eqn{m x 1} vector of the initial values.
#' @param Sigma_w_init a \eqn{m x m} variance-covariance matrix of the initial parameter values.
#' 
#' @details For the state space model with the measurement equation
#' \deqn{y_t = Z_t a_t + v_t}
#' and the transition equation 
#' \deqn{a_{t+1} = B_t a_t + w_t,}
#' where \eqn{v_t \sim N(0, \Sigma_{v_t})} and \eqn{w_t \sim N(0, \Sigma_{w_t})} the
#' function produces a draw of the state vector \eqn{a_t} for \eqn{T = 1,...,T}.
#' 
#' @return A \eqn{m x T} matrix of parameter values.
#' 
#' @references
#' 
#' Durbin, J., & Koopman, S. J. (2002). A simple and efficient simulation smoother for state space time series analysis. \emph{Biometrika}, 89(3), 603--615.
#' 
kalman_dk <- function(y, Z, Sigma_v, Sigma_w, B, a_init, Sigma_w_init) {
    .Call(`_bvartools_kalman_dk`, y, Z, Sigma_v, Sigma_w, B, a_init, Sigma_w_init)
}

#' Gaussian Log-Likelihood
#' 
#' Calculates the log likelihood of a multivariate Gaussian process.
#' 
#' @param y an \eqn{n x T} matrix of residuals, where \eqn{n} is the number of
#' variables and \eqn{T} is the total amount of observations.
#' @param Sigma a constant \eqn{n x n} or time varying \eqn{nT x n} variance-covariance matrix.
#' @param Sigma_i the inverse of Sigma.
#' 
#' @return A vector of log likelihoods for each period.
#' 
loglik_gauss <- function(y, Sigma, Sigma_i) {
    .Call(`_bvartools_loglik_gauss`, y, Sigma, Sigma_i)
}

#' Posterior Draw of Cointegration Parameters
#' 
#' Produces a draw from a posterior density Koop et al. (2010).
#' 
#' @param y a \eqn{k \times T} matrix of differenced dependent variables.
#' @param beta a \eqn{k_{ect} \times r} matrix of variables in the error correction term.
#' @param ect a \eqn{k_{ect} \times T} matrix of regressor variables in levels and deterministic terms in the error correction term.
#' @param x a \eqn{k_{x} \times T} matrix of differenced regressor variables and unrestriced deterministic terms.
#' @param Sigma_i a \eqn{k \times k} variance-covariance matrix.
#' @param Gamma_mu_prior a \eqn{kk_{x} \times 1} prior mean vector of non-cointegration coefficients.
#' @param Gamma_V_i_prior a \eqn{kk_{x} \times kk_{x}} inverted prior covariance vector of non-cointegration coefficients.
#' @param v_i a numeric between 0 and 1 specifying the shrinkage.
#' @param P_tau_i a \eqn{k_{ect} \times k_{ect}} inverted matrix specifying the central location of \eqn{sp(\beta)}.
#' @param G_i a \eqn{k \times k} matrix.
#' 
#' @details The function produces a draw of coefficients for the model
#' \deqn{\Delta y_t = \alpha \beta' ECT_{t} + \Gamma X_{t} + u_t,}
#' where \eqn{\Delta y_t} is a \eqn{k \times 1} vector of differenced dependent variables,
#' \eqn{\alpha} is a \eqn{k \times r} loading matrix,
#' \eqn{\beta} is a \eqn{k_{ect} \times r} cointegration matrix,
#' \eqn{ECT_t} is a \eqn{k_{ect} \times 1} vector of regressors in the error correction term,
#' \eqn{\Gamma} is a \eqn{k \times k_{x}} matrix of non-cointegration parameters,
#' \eqn{X_t} is a \eqn{k_{x} \times 1} vector of non-cointegration regressors,
#' and \eqn{u_t} is a \eqn{k \times 1} error term.
#' 
#' @return A list containing the following elements:
#' \item{alpha}{a draw of the \eqn{k \times r} loading matrix.}
#' \item{beta}{a draw of the \eqn{k_{ect} \times r} cointegration matrix.}
#' \item{Pi}{a draw of the \eqn{k \times k_{ect}} matrix \eqn{\Pi = \alpha \beta'}.}
#' \item{Gamma}{a draw of the \eqn{k \times k_{x}} coefficient matrix for non-cointegration parameters.}
#' 
#' @references
#' 
#' Koop, G., León-González, R., & Strachan R. W. (2010). Efficient posterior
#' simulation for cointegrated models with priors on the cointegration space.
#' \emph{Econometric Reviews}, 29(2), 224-242. \url{https://doi.org/10.1080/07474930903382208}
#' 
post_koop_2010 <- function(y, beta, ect, x, Sigma_i, Gamma_mu_prior, Gamma_V_i_prior, v_i, P_tau_i, G_i) {
    .Call(`_bvartools_post_koop_2010`, y, beta, ect, x, Sigma_i, Gamma_mu_prior, Gamma_V_i_prior, v_i, P_tau_i, G_i)
}

#' Posterior Draw from Normal Distribution
#' 
#' Produces a draw from a posterior density of a Gaussian process and normal prior.
#' 
#' @param y \eqn{n x T} matrix containing the time series of the dependent variable.
#' @param x \eqn{k x T} matrix containing the time series of the explanatory variables.
#' @param Sigma_i inverse of the \eqn{n x n} variance-covariance matrix.
#' @param mu_prior \eqn{m x 1} numeric vector containing the prior mean of the coefficients.
#' @param V_i_prior inverse of the \eqn{m x m} covariance matrix of the coefficients.
#' 
#' @details The function produces a vectorised draw of the \eqn{n x k} coefficient
#' matrix \eqn{A} of the model
#' \deqn{y_{t} = A x_{t} a + \epsilon_{t},}
#' where \eqn{y_{t}} is a \eqn{n x 1} vector of endogenous variables in period \eqn{t},
#' \eqn{x_{t}} is a \eqn{k x 1} vector of explanatory variables, and the error term
#' \eqn{\epsilon_{t}} is normally distributed with zero mean and variance-covariance
#' matrix \eqn{\Sigma}. \eqn{k} is the number of explanatory variables and \eqn{m} it
#' the total number of estimated coefficients.
#' 
#' @return A \eqn{m x 1} vector of coefficient values.
#' 
post_normal <- function(y, x, Sigma_i, mu_prior, V_i_prior) {
    .Call(`_bvartools_post_normal`, y, x, Sigma_i, mu_prior, V_i_prior)
}

#' Posterior Draw from Normal Distribution (SUR)
#' 
#' Produces a draw from a posterior density of a Gaussian process with normal prior
#' using seemingly unlelated regression.
#' 
#' @param y \eqn{n x T} matrix containing the time series of the dependent variable.
#' @param Z \eqn{nT x m} matrix containing the time series of the explanatory variables.
#' @param Sigma_i inverse of the \eqn{n x n} or \eqn{nT x n} variance-covariance matrix.
#' @param bprior \eqn{m x 1} numeric vector containing the prior mean of the coefficients.
#' @param Vprior_i inverse of the \eqn{m x m} covariance matrix of the coefficients.
#' 
#' @details The function produces a draw of the \eqn{m x 1} coefficient vector \eqn{a}
#' of the model
#' \deqn{y_{t} = Z_{t} a + \epsilon_{t},}
#' where \eqn{y_{t}} is a \eqn{n x 1} vector of endogenous variables in period \eqn{t},
#' \eqn{Z_{t}} is a \eqn{n x mn} matrix of explanatory variables, and the error term
#' \eqn{\epsilon_{t}} is normally distributed with zero mean and variance-covariance
#' matrix \eqn{\Sigma_{t}}.
#' 
#' @return A \eqn{m x 1} vector of coefficient values.
#' 
post_normal_sur <- function(y, Z, Sigma_i, bprior, Vprior_i) {
    .Call(`_bvartools_post_normal_sur`, y, Z, Sigma_i, bprior, Vprior_i)
}

